import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { FieldValue } from '@/lib/mongo-website-types.mjs';
import { NextRequest, NextResponse } from 'next/server';
import { getWebsiteDatabase, serializeDatabaseDocument } from '@/lib/website-database';

const collection = 'websitePageHeroes';
async function find(page: string) { const snapshot = await getWebsiteDatabase().collection(collection).where('page', '==', page).limit(1).get(); return snapshot.empty ? null : snapshot.docs[0]; }
export async function GET(req: NextRequest) { try { const page = new URL(req.url).searchParams.get('page'); if (!page) return NextResponse.json({ error: 'Page parameter is required' }, { status: 400 }); const snapshot = await find(page); const data = snapshot?.data(); return NextResponse.json({ hero: snapshot && data?.isActive !== false ? serializeDatabaseDocument(snapshot.id, data as Record<string, unknown>) : null }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to fetch hero' }, { status: 503 }); } }
export async function POST(req: NextRequest) { try { if (!(await getServerSession(authOptions))) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await req.json(); const { page, title, subtitle, description } = body; if (!page || !title || !subtitle || !description) return NextResponse.json({ error: 'Missing required fields: page, title, subtitle, description' }, { status: 400 }); if (await find(page)) return NextResponse.json({ error: 'Hero section already exists for this page. Use PUT to update.' }, { status: 400 }); const ref = getWebsiteDatabase().collection(collection).doc(); const payload = { ...body, buttonText: body.buttonText || 'Buy Plan', buttonLink: body.buttonLink || '/appointment', image: body.image || null, isActive: body.isActive !== false, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }; await ref.set(payload); return NextResponse.json(serializeDatabaseDocument(ref.id, { ...payload, createdAt: new Date().toISOString(), updatedAt: new Date().toISOString() }), { status: 201 }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to create hero' }, { status: 503 }); } }
export async function PUT(req: NextRequest) { try { if (!(await getServerSession(authOptions))) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const body = await req.json(); if (!body.page) return NextResponse.json({ error: 'Page is required' }, { status: 400 }); const snapshot = await find(body.page); if (!snapshot) return NextResponse.json({ error: 'Hero section not found for this page' }, { status: 404 }); const { page: _page, ...updateData } = body; await snapshot.ref.update({ ...updateData, updatedAt: FieldValue.serverTimestamp() }); const updated = await snapshot.ref.get(); return NextResponse.json(serializeDatabaseDocument(snapshot.id, updated.data() as Record<string, unknown>)); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to update hero' }, { status: 503 }); } }
export async function DELETE(req: NextRequest) { try { if (!(await getServerSession(authOptions))) return NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); const page = new URL(req.url).searchParams.get('page'); if (!page) return NextResponse.json({ error: 'Page parameter is required' }, { status: 400 }); const snapshot = await find(page); if (!snapshot) return NextResponse.json({ error: 'Hero section not found' }, { status: 404 }); await snapshot.ref.delete(); return NextResponse.json({ message: 'Hero section deleted successfully' }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to delete hero' }, { status: 503 }); } }
