const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),ts=require('typescript'),vm=require('node:vm');
function harness(){
 const docs=new Map(),transactions=[],calls={providerOrders:[],notices:0,capi:0,reads:0};let session=null,proof={id:'pay_1',order_id:'rzp_1',amount:249900,currency:'INR',status:'captured',method:'card',created_at:1700000000},beforeTransaction=null;
 const clone=d=>d===undefined?undefined:structuredClone(d);
 const snapshot=(path)=>({id:path.split('/').at(-1),ref:ref(path),exists:docs.has(path),data:()=>clone(docs.get(path)),get:key=>clone(docs.get(path)?.[key])});
 function query(collection,filters=[]){return {where:(field,op,value)=>query(collection,[...filters,[field,op,value]]),limit:()=>query(collection,filters),get:async()=>{calls.reads++;const found=[...docs].filter(([path,d])=>path.startsWith(collection+'/')&&filters.every(([field,op,value])=>op==='=='?d[field]===value:false)).map(([path])=>snapshot(path));return {docs:found,empty:!found.length,size:found.length};}};}
 function apply(path,data,merge=false){const next=merge?clone(docs.get(path)||{}):{};for(const [k,v] of Object.entries(data))next[k]=v?.__increment!==undefined?(next[k]||0)+v.__increment:clone(v);docs.set(path,next);}
 function ref(path){return {id:path.split('/').at(-1),path,get:async()=>{calls.reads++;return snapshot(path);},set:async(data,options)=>apply(path,data,options?.merge),delete:async()=>docs.delete(path)};}
 const db={collection:name=>({...query(name),doc:id=>ref(name+'/'+id)}),runTransaction:async fn=>{if(beforeTransaction){const f=beforeTransaction;beforeTransaction=null;f();}const writes=[];const value=await fn({get:async target=>{assert.equal(writes.length,0,'Firestore reads must precede writes');return target.path?snapshot(target.path):target.get();},set:(r,d,o)=>writes.push({r,d,merge:o?.merge}),update:(r,d)=>writes.push({r,d,merge:true})});for(const w of writes)apply(w.r.path,w.d,w.merge);transactions.push(writes.map(w=>w.r.path));return value;}};
 const firebase={getWebsiteFirestore:()=>db,serializeFirestoreDocument:(id,data)=>({_id:id,...data})};
 const mocks={'server-only':{},'next-auth':{getServerSession:async()=>session},'@/lib/auth':{authOptions:{}},'firebase-admin/firestore':{FieldValue:{serverTimestamp:()=>new Date('2026-01-01'),increment:n=>({__increment:n})}},'next/server':{NextResponse:{json:(body,init)=>new Response(JSON.stringify(body),{status:init?.status||200,headers:{'content-type':'application/json'}})}},uuid:{v4:()=> 'order_created'},razorpay:class{orders={create:async p=>(calls.providerOrders.push(p),{id:'rzp_created',amount:p.amount})};payments={fetch:async()=>clone(proof)};},'@/lib/firebase-admin':firebase,'./firebase-admin':firebase,'@/lib/admin-date-range':{buildIndiaCreatedAtRange:()=>null},'@/lib/coupons':{calculateSubtotal:products=>products.reduce((sum,p)=>sum+p.price*p.quantity,0),validateCouponForProducts:async()=>{throw Error('Unexpected coupon provider');}},'@/lib/notifications':{sendPostPaymentNotifications:async()=>{calls.notices++;}},'@/lib/meta-capi':{sendCapiEvent:async()=>{calls.capi++;},deriveFbcFromUrl:()=>null,getClientIp:()=>null}};
 function load(path){const module={exports:{}};const compiled=ts.transpileModule(fs.readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;vm.runInThisContext('(function(require,module,exports){'+compiled+'\n})')(name=>{if(name in mocks)return mocks[name];if(name==='@/lib/website-admin-repository')return load('lib/website-admin-repository.ts');if(name==='./permanent-admin')return {getPermanentAdminConfig:()=>null};if(name==='./security')return {sanitizeText:s=>s};if(name==='bcryptjs')return require(name);if(name==='@/lib/checkout-catalog')return load('lib/checkout-catalog.ts');if(name==='@/lib/payment-verification')return load('lib/payment-verification.ts');throw Error('Unmocked dependency '+name);},module,module.exports);return module.exports;}
 const api=load('app/api/orders/route.ts'),request=(data={},method='POST',suffix='')=>{const req=new Request('http://localhost/api/orders'+suffix,{method,...(method==='GET'?{}:{body:JSON.stringify(data)})});req.cookies={get:()=>undefined};return req;};
 function order(status='pending'){docs.set('websiteOrders/order_1',{orderId:'order_1',razorpayOrderId:'rzp_1',total:2499,paymentStatus:status,customerName:'Test',customerEmail:'test@example.test',customerPhone:'0000000000',coupon:{code:'TEST'},products:[]});docs.set('websiteCoupons/coupon_1',{code:'TEST',usedCount:0});}
 return {api,paymentApi:load('app/api/payments/route.ts'),request,docs,calls,transactions,order,setProof:p=>proof={...proof,...p},setSession:s=>session=s,beforeTransaction:f=>beforeTransaction=f};
}
test('checkout ignores client-supplied price/name and uses active server catalogue',async()=>{const h=harness();h.docs.set('websitePricing/plan_1',{planName:'Verified plan',price:2499,isActive:true,duration:'1 month'});const res=await h.api.POST(h.request({action:'create',customerName:'Test',customerEmail:'test@example.test',customerPhone:'0000000000',total:1,products:[{id:'plan_1',name:'Forged',price:1,quantity:2}]}));assert.equal(res.status,200);assert.equal(h.calls.providerOrders[0].amount,499800);const order=h.docs.get('websiteOrders/order_created');assert.equal(order.total,4998);assert.equal(order.products[0].name,'Verified plan');});
test('unauthenticated listing and deletion never touch database',async()=>{const h=harness();for(const [method,data] of [['GET',{}],['DELETE',{orderId:'order_1'}],['PATCH',{action:'bulkDelete',orderIds:['order_1']}]] ){const res=await h.api[method](h.request(data,method));assert.equal(res.status,401);}assert.equal(h.calls.reads,0);});
test('capture commits order, payment and coupon atomically; replay has no duplicate increment/send',async()=>{const h=harness();h.order();const body={action:'verify',orderId:'order_1',razorpayOrderId:'rzp_1',razorpayPaymentId:'pay_1'};assert.equal((await h.api.POST(h.request(body))).status,200);assert.deepEqual(h.transactions[0].sort(),['websiteCoupons/coupon_1','websiteOrders/order_1','websitePayments/pay_1']);assert.equal(h.docs.get('websiteOrders/order_1').paymentStatus,'completed');assert.equal(h.docs.get('websitePayments/pay_1').status,'completed');assert.equal((await h.api.POST(h.request(body))).status,200);assert.equal(h.docs.get('websiteCoupons/coupon_1').usedCount,1);assert.equal(h.calls.notices,1);assert.equal(h.calls.capi,1);});
test('failed provider response and client resolve cannot downgrade a completed order',async()=>{const h=harness();h.order();const body={action:'verify',orderId:'order_1',razorpayOrderId:'rzp_1',razorpayPaymentId:'pay_1'};await h.api.POST(h.request(body));h.setProof({status:'failed'});assert.equal((await h.api.POST(h.request(body))).status,409);await h.api.POST(h.request({action:'resolve',orderId:'order_1',status:'failed',razorpayPaymentId:'forged',responseData:{status:'captured'}}));assert.equal(h.docs.get('websiteOrders/order_1').paymentStatus,'completed');assert.equal(h.docs.get('websitePayments/pay_1').status,'completed');assert.equal(h.docs.get('websiteCoupons/coupon_1').usedCount,1);assert.equal(h.docs.size,3);});
test('mismatched provider amount is rejected without any settlement writes',async()=>{const h=harness();h.order();h.setProof({amount:1});const res=await h.api.POST(h.request({action:'verify',orderId:'order_1',razorpayOrderId:'rzp_1',razorpayPaymentId:'pay_1'}));assert.equal(res.status,400);assert.equal(h.transactions.length,0);assert.equal(h.docs.get('websiteOrders/order_1').paymentStatus,'pending');});

test('current stored viewer cannot delete despite stale superadmin session claim',async()=>{const h=harness();h.setSession({user:{email:'viewer@example.test',role:'superadmin'}});h.docs.set('websiteAdmins/viewer',{email:'viewer@example.test',role:'viewer'});h.order();for(const method of ['DELETE','PATCH']){const res=await h.api[method](h.request(method==='DELETE'?{orderId:'order_1'}:{action:'bulkDelete',orderIds:['order_1']},method));assert.equal(res.status,403);}assert.equal(h.docs.get('websiteOrders/order_1').paymentStatus,'pending');});
test('transaction revalidates changed order price before any settlement writes',async()=>{const h=harness();h.order();h.beforeTransaction(()=>h.docs.get('websiteOrders/order_1').total=5000);const res=await h.api.POST(h.request({action:'verify',orderId:'order_1',razorpayOrderId:'rzp_1',razorpayPaymentId:'pay_1'}));assert.equal(res.status,500);assert.equal(h.docs.has('websitePayments/pay_1'),false);assert.equal(h.docs.get('websiteCoupons/coupon_1').usedCount,0);assert.equal(h.docs.get('websiteOrders/order_1').paymentStatus,'pending');});
test('existing payment identity cannot be rebound to a different order',async()=>{const h=harness();h.order();h.docs.set('websitePayments/pay_1',{orderId:'other',razorpayOrderId:'other_provider',status:'completed'});const res=await h.api.POST(h.request({action:'verify',orderId:'order_1',razorpayOrderId:'rzp_1',razorpayPaymentId:'pay_1'}));assert.equal(res.status,500);assert.equal(h.docs.get('websitePayments/pay_1').orderId,'other');assert.equal(h.docs.get('websiteCoupons/coupon_1').usedCount,0);});

test('payment listing rejects missing and deleted admin sessions but permits an established viewer',async()=>{const h=harness();assert.equal((await h.paymentApi.GET(h.request({},'GET'))).status,401);h.setSession({user:{email:'viewer@example.test',role:'admin'}});h.docs.set('websiteAdmins/viewer',{email:'viewer@example.test',role:'viewer',isDeleted:true});assert.equal((await h.paymentApi.GET(h.request({},'GET'))).status,401);h.docs.get('websiteAdmins/viewer').isDeleted=false;assert.equal((await h.paymentApi.GET(h.request({},'GET'))).status,200);});

test('trial checkout resolves the public slug to the confirmed 299 INR ten-day plan',async()=>{
 const h=harness();
 const plan=JSON.parse(fs.readFileSync('data/firebase-website-plans.json','utf8')).find(p=>p.id==='weight-loss-10-days-trial-299');
 h.docs.set('websitePricing/'+plan.id,plan);
 const res=await h.api.POST(h.request({action:'create',customerName:'Test',customerEmail:'test@example.test',customerPhone:'0000000000',products:[{id:'weight-loss-weight-loss-10-days-trial',price:1,quantity:1}]}));
 assert.equal(res.status,200);assert.equal(h.calls.providerOrders[0].amount,29900);
 assert.equal(h.docs.get('websiteOrders/order_created').products[0].duration,'10 days');
});

test('PCOD checkout uses temporary catalogue rates and rejects unpriced plans',async()=>{
 for(const [months,price] of [[1,2999],[3,7999],[6,14999]]){
  const h=harness(),plan=JSON.parse(fs.readFileSync('data/firebase-website-plans.json','utf8')).find(p=>p.id===`pcod-pcos-${months}-month`);
  h.docs.set('websitePricing/'+plan.id,plan);
  const res=await h.api.POST(h.request({action:'create',customerName:'Test',customerEmail:'test@example.test',customerPhone:'0000000000',products:[{id:plan.id,price:1,quantity:1}]}));
  assert.equal(res.status,200);assert.equal(h.calls.providerOrders[0].amount,price*100);
 }
 const h=harness();h.docs.set('websitePricing/unpriced',{planName:'Unpriced',price:0,pricePending:true,isActive:true});
 const res=await h.api.POST(h.request({action:'create',customerName:'Test',customerEmail:'test@example.test',customerPhone:'0000000000',products:[{id:'unpriced',quantity:1}]}));
 assert.notEqual(res.status,200);assert.equal(h.calls.providerOrders.length,0);
});
