import { FieldValue } from '@/lib/mongo-website-types.mjs';
import { NextRequest, NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth';
import { getWebsiteDatabase, serializeDatabaseDocument } from '@/lib/website-database';

export const dynamic = 'force-dynamic';
export const revalidate = 0;
const collection = 'websitePlanBanners';
async function requireSession() { return (await getServerSession(authOptions)) ? null : NextResponse.json({ error: 'Unauthorized' }, { status: 401 }); }
export async function GET(request: NextRequest) { try { const { searchParams } = new URL(request.url); const page = searchParams.get('page'); const planId = searchParams.get('planId'); const active = searchParams.get('active'); const banners = (await getWebsiteDatabase().collection(collection).get()).docs.map((doc) => serializeDatabaseDocument(doc.id, doc.data() as Record<string, unknown>)).filter((banner: any) => (!page || banner.page === page) && (!planId || banner.planId === planId) && (active !== 'true' || banner.isActive === true)).sort((a: any, b: any) => Number(a.order || 0) - Number(b.order || 0) || String(b.createdAt || '').localeCompare(String(a.createdAt || ''))); return NextResponse.json({ success: true, banners }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to fetch plan banners' }, { status: 503 }); } }
export async function POST(request: NextRequest) { const unauthorized = await requireSession(); if (unauthorized) return unauthorized; try { const body = await request.json(); if (!body.planId || !body.page) return NextResponse.json({ error: 'planId and page are required' }, { status: 400 }); const db = getWebsiteDatabase(); const ref = db.collection(collection).doc(); const old = await db.runTransaction(async tx => { const existing = await tx.get(db.collection(collection).where('planId', '==', body.planId)); const matching = existing.docs.filter(doc => doc.data().page === body.page); for (const doc of matching) tx.delete(doc.ref); tx.create(ref, { ...body, createdAt: FieldValue.serverTimestamp(), updatedAt: FieldValue.serverTimestamp() }); return matching.length > 0; }); return NextResponse.json({ success: true, banner: serializeDatabaseDocument(ref.id, body), message: old ? 'Previous banner deleted and new one created' : 'Banner created' }, { status: 201 }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to create plan banner' }, { status: 503 }); } }
export async function PUT(request: NextRequest) { const unauthorized = await requireSession(); if (unauthorized) return unauthorized; try { const { id, ...updateData } = await request.json(); if (!id) return NextResponse.json({ error: 'Banner ID is required' }, { status: 400 }); const ref = getWebsiteDatabase().collection(collection).doc(id); if (!(await ref.get()).exists) return NextResponse.json({ error: 'Banner not found' }, { status: 404 }); await ref.update({ ...updateData, updatedAt: FieldValue.serverTimestamp() }); const updated = await ref.get(); return NextResponse.json({ success: true, banner: serializeDatabaseDocument(id, updated.data() as Record<string, unknown>) }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to update plan banner' }, { status: 503 }); } }
export async function DELETE(request: NextRequest) { const unauthorized = await requireSession(); if (unauthorized) return unauthorized; try { const id = new URL(request.url).searchParams.get('id'); if (!id) return NextResponse.json({ error: 'Banner ID is required' }, { status: 400 }); const ref = getWebsiteDatabase().collection(collection).doc(id); if (!(await ref.get()).exists) return NextResponse.json({ error: 'Banner not found' }, { status: 404 }); await ref.delete(); return NextResponse.json({ success: true, message: 'Banner deleted successfully' }); } catch (error: any) { return NextResponse.json({ error: error?.message || 'Failed to delete plan banner' }, { status: 503 }); } }
